#pragma once
#include "CoreMinimal.h"
#include "DiscordClientProvisionalUserMergeRequiredCallbackMulticastDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_MULTICAST_DELEGATE(FDiscordClientProvisionalUserMergeRequiredCallbackMulticast);

