#pragma once
#include "CoreMinimal.h"
#include "DiscordClientOpenConnectedGamesSettingsInDiscordCallbackMulticastDelegate.generated.h"

class UDiscordClientResult;

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FDiscordClientOpenConnectedGamesSettingsInDiscordCallbackMulticast, UDiscordClientResult*, Result);

