#pragma once
#include "CoreMinimal.h"
#include "DiscordClientAuthorizeDeviceScreenClosedCallbackMulticastDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_MULTICAST_DELEGATE(FDiscordClientAuthorizeDeviceScreenClosedCallbackMulticast);

