import os, subprocess, textwrap

OUT = os.environ['SCRATCH'] + '/icons'
os.makedirs(OUT, exist_ok=True)
SZ = 48  # glyph raster size

# Original, simple white glyphs (tinted per-category at runtime via SetColorAndOpacity).
# Each is a white shape on transparent; drop shadow-ish dark stroke for contrast.
GLYPHS = {
    # generic filled marker (default / ores use tint to differentiate)
    'pin':   '<circle cx="24" cy="24" r="15" fill="#fff" stroke="#0008" stroke-width="3"/>',
    # gem / effigy: diamond
    'gem':   '<path d="M24 6 L40 20 L24 42 L8 20 Z" fill="#fff" stroke="#0008" stroke-width="3" stroke-linejoin="round"/>',
    # note: document
    'note':  '<rect x="12" y="8" width="24" height="32" rx="3" fill="#fff" stroke="#0008" stroke-width="3"/><path d="M17 17 H31 M17 24 H31 M17 31 H27" stroke="#0006" stroke-width="2.4" stroke-linecap="round"/>',
    # egg
    'egg':   '<path d="M24 7 C34 7 38 24 38 30 A14 14 0 0 1 10 30 C10 24 14 7 24 7 Z" fill="#fff" stroke="#0008" stroke-width="3"/>',
    # chest
    'chest': '<rect x="9" y="18" width="30" height="20" rx="2" fill="#fff" stroke="#0008" stroke-width="3"/><path d="M9 24 H39" stroke="#0007" stroke-width="2.6"/><path d="M9 18 Q24 8 39 18" fill="#fff" stroke="#0008" stroke-width="3"/><rect x="21" y="22" width="6" height="7" rx="1" fill="#0007"/>',
    # oil: droplet
    'drop':  '<path d="M24 7 C33 20 34 25 34 30 A10 10 0 0 1 14 30 C14 25 15 20 24 7 Z" fill="#fff" stroke="#0008" stroke-width="3"/>',
    # coin
    'coin':  '<circle cx="24" cy="24" r="15" fill="#fff" stroke="#0008" stroke-width="3"/><circle cx="24" cy="24" r="8" fill="none" stroke="#0007" stroke-width="2.4"/>',
    # lotus / fruit: flower
    'flower':'<g fill="#fff" stroke="#0008" stroke-width="2.4"><circle cx="24" cy="14" r="6"/><circle cx="14" cy="21" r="6"/><circle cx="34" cy="21" r="6"/><circle cx="18" cy="32" r="6"/><circle cx="30" cy="32" r="6"/></g><circle cx="24" cy="24" r="5" fill="#0007"/>',
    # tree
    'tree':  '<path d="M24 6 L36 26 H30 L38 40 H10 L18 26 H12 Z" fill="#fff" stroke="#0008" stroke-width="3" stroke-linejoin="round"/>',
    # flag / outpost
    'flag':  '<path d="M15 8 V42" stroke="#0008" stroke-width="4" stroke-linecap="round"/><path d="M17 9 H37 L31 17 L37 25 H17 Z" fill="#fff" stroke="#0008" stroke-width="2.6" stroke-linejoin="round"/>',
}

def svg(inner):
    return f'<svg xmlns="http://www.w3.org/2000/svg" width="{SZ}" height="{SZ}" viewBox="0 0 48 48">{inner}</svg>'

blobs = {}
for name, inner in GLYPHS.items():
    sp = f'{OUT}/{name}.svg'; pp = f'{OUT}/{name}.png'
    open(sp, 'w').write(svg(inner))
    subprocess.run(['rsvg-convert', '-w', str(SZ), '-h', str(SZ), sp, '-o', pp], check=True)
    blobs[name] = open(pp, 'rb').read()

# emit C++ header
hdr = ['// Generated by tools/icons/gen_icons.py - original glyphs, white for tinting',
       '#pragma once', '#include <cstdint>', '#include <cstddef>', '',
       'namespace CairnMap::Icons {', 'struct Blob { const uint8_t* data; size_t size; };', '']
for name, data in blobs.items():
    arr = ','.join(str(b) for b in data)
    hdr.append(f'inline constexpr uint8_t k_{name}[] = {{{arr}}};')
hdr.append('')
for name in blobs:
    hdr.append(f'inline constexpr Blob {name.upper()}{{k_{name}, sizeof(k_{name})}};')
hdr.append('} // namespace CairnMap::Icons')
open(os.environ['SCRATCH'] + '/cairn_icons.hpp', 'w').write('\n'.join(hdr))

tot = sum(len(v) for v in blobs.values())
print('glyphs:', list(blobs.keys()))
print('total bytes:', tot, ' (avg', tot//len(blobs), 'per glyph)')
