#include "PalBaseCampPassiveEffect_SanityDecreaseSuppressor_Watchtower.h"

UPalBaseCampPassiveEffect_SanityDecreaseSuppressor_Watchtower::UPalBaseCampPassiveEffect_SanityDecreaseSuppressor_Watchtower() {
}


