#include "PalMapObjectFarmBlockRecipeDropItemSpawnPointComponent.h"

UPalMapObjectFarmBlockRecipeDropItemSpawnPointComponent::UPalMapObjectFarmBlockRecipeDropItemSpawnPointComponent(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
}


