#include "PalMapObjectBaseCampPassiveEffectSanityWatchtowerParameterComponent.h"

UPalMapObjectBaseCampPassiveEffectSanityWatchtowerParameterComponent::UPalMapObjectBaseCampPassiveEffectSanityWatchtowerParameterComponent(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
}


