#pragma once
#include "CoreMinimal.h"
#include "EPalDipType.generated.h"

UENUM()
enum class EPalDipType : uint16 {
    None,
    ReloadSpeedDisp,
    ReloadSpeedX,
    BuildingDamageReductionDisp,
    Fishing_GoodTalentPalProbability,
    DummyBlockUserList,
    Disp_BP_ExplosionAttackBase,
    Bugfix_BP_ExplosionAttackBase,
    Disp_Status_ToxicGas,
    Disp_ExplosiveSpore,
    PauseSpawn_ExplosiveSpore,
    DisableCollision_ExplosiveSpore,
    FreezePatrol_ExplosiveSpore,
    WarnIfOutOfVolume_ExplosiveSpore,
    DispPatrol_ExplosiveSpore,
    DispLocalPatrol_ExplosiveSpore,
    Disp_Status_LowGravity,
    Disp_Status_JumpingFlog,
    Disp_LifeDrainPower,
    Disp_NightVision,
    Enable_Skill_Defuser_ExplosiveSpore,
    Disp_AvoidDurationUp,
    Test_AvoidDurationUp,
    Force_EnableBuildingNameDisplay,
    CountSporesInScreen,
    DIP_025,
    DIP_026,
    DIP_027,
    DIP_028,
    DIP_029,
    DIP_030,
    DIP_031,
    DIP_032,
    DIP_033,
    DIP_034,
    DIP_035,
    DIP_036,
    DIP_037,
    DIP_038,
    DIP_039,
    DIP_040,
    DIP_041,
    DIP_042,
    DIP_043,
    DIP_044,
    DIP_045,
    DIP_046,
    DIP_047,
    DIP_048,
    DIP_049,
};

