#pragma once
#include "CoreMinimal.h"
#include "EPalFoliagePresetType.generated.h"

UENUM(BlueprintType)
enum class EPalFoliagePresetType : uint8 {
    None,
    NormalTree_L,
    LowTree,
    NormalTree_L_CherryBlossom,
    Mushroom_L,
    Mushroom_S,
    NormalTree_L_Red,
    NormalTree_L_Yellow,
    NormalTree_L_Pink,
    NormalTree_L_Dead,
    NormalTree_L_Snow,
    FineTree_L,
    FineTree_L_CherryBlossom,
    FineTree_L_Red,
    FineTree_L_Yellow,
    FineTree_L_Pink,
    FineTree_L_Dead,
    FineTree_L_Snow,
    WorldTree_L,
    WorldTree_L_CherryBlossom,
    WorldTree_L_Red,
    WorldTree_L_Yellow,
    WorldTree_L_Pink,
    WorldTree_L_Dead,
    WorldTree_L_Snow,
    WorldTree_L_Yellow2,
    WorldTree_L_Purple,
    WorldTree_L_Orange,
    FineTree_L_Blue,
    FineTree_L_Purple,
    FineTree_L_DeepGreen,
    WildlifeSanctuaryTree_L,
    WorldTree_L_Yellow_2,
    WorldTree_L_Yellow2_2,
    WorldTree_L_2,
    WorldTree_L_Orange_2,
    WorldTree_L_Snow_2,
    WorldTree_L_Dead_2,
    FineTree_L_TreeSea,
};

