#pragma once
#include "CoreMinimal.h"
#include "EPalVisualEffectID.generated.h"

UENUM(BlueprintType)
enum class EPalVisualEffectID : uint8 {
    None,
    CaptureEmissive,
    SpawnFromBallEmissive,
    ReturnToBallEmissive,
    FadeOut,
    FadeIn,
    PalOutlineFadeIn,
    PalOutlineFadeOut,
    PalBattleOutline,
    Poison,
    PowerUp,
    AttackUp,
    DefenseUp,
    AttackDown,
    DeadEffect,
    FireCondition,
    WaterCondition,
    IceCondition,
    ElectricityCondition,
    EarthCondition,
    LeafCondition,
    DarkCondition,
    Swimming,
    HoveringWater,
    CameraVignette,
    PalEffectFadeIn,
    PalEffectFadeOut,
    RarePal,
    FunnelStartEmissive,
    FunnelEndEmissive,
    SelfDestructEmissive,
    Mosaic,
    ChangeElement_Ice,
    ChangeElement_Normal,
    ChangeElement_Fire,
    ChangeElement_Water,
    ChangeElement_Leaf,
    ChangeElement_Electricity,
    ChangeElement_Earth,
    ChangeElement_Dark,
    ChangeElement_Dragon,
    PalEnhancement,
    TempEffect,
    LavaDamage,
    AcidDamage,
    Teleport_FadeIn,
    Teleport_FadeOut,
    WorldTreeAura,
    AwakeningAura,
    AttackRateHPThreshold,
    DefenseRateHPThreshold,
    RecoverHPOnHPThreshold,
    BulletStackBuff,
    DefeatStackBuff,
    LifeDrainPower_AttackUp,
    LowGravity,
    PlayerCommonBuff,
    DebugRefresh,
};

