#pragma once
#include "CoreMinimal.h"
#include "EPalAudioState.generated.h"

UENUM(BlueprintType)
enum class EPalAudioState : uint8 {
    None,
    VillageA,
    VillageB,
    BaseCamp,
    InDoor,
    BossRoom,
    Grassland,
    Forest,
    Desert,
    Mountain,
    Caution,
    Fight,
    End,
    Arena_PartySelect,
    Arena_PreBattle,
    Arena_InBattle,
    Arena_Result,
    Battle_Cute,
    Battle_Cool,
    Battle_Strong,
    Battle_Human_Common,
    Battle_Human_Villain,
    Battle_FieldBoss_Tier_1,
    Battle_FieldBoss_Tier_2,
    Battle_FieldBoss_Tier_3,
    Battle_FieldBoss_Tier_4,
    Battle_FieldBoss_Tier_5,
    Battle_Predator,
    Battle_EyeofCthulhu,
    Battle_Machine,
    Battle_Legend,
    Battle_KingWhale,
    Battle_RaidBoss,
    Battle_TowerBoss,
    Battle_RaidBoss_KingBahamut,
    Battle_RaidBoss_DarkMechaDragon,
    Battle_RaidBoss_Moonlord,
    Battle_RaidBoss_LegendDeer,
    Battle_RaidBoss_LegendDeer2,
    Battle_WorldTreeDragon,
    Explore,
    Battle,
    Alive,
    Dead,
};

